### ISSUE TITLE
mod_ratio availability in data.indiv_proba.csv

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/m6anet#107]
I realized that, unlike data.site_proba.csv, data.indiv_proba.csv doesn't include **mod_ratio** result.
I wonder if **mod_ratio** can be supported in the data.site_proba.csv result.
How can I get m6A methylation level from data.indiv_proba.csv?

**Comment by chrishendra93** [comment]
hi @sunsetyerin ,

data.indiv_proba.csv does not contain mod ratio since each row describes read level probability score. So if you need an estimate for how likely each read to be modified, the probability_modified column in data.indiv_proba.csv will tell you that. The mod ratio in data.site_proba.csv is derived by thresholding the read probability score and calculating the number of reads that are modified from each site
