### ISSUE TITLE
Previously generated xpore-dataprep files suitable for m6anet inference

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/m6anet#2]
This seems like a great tool and I could work through the demo data with no issues. I had actually generated some data using the `xpore` repository on my own data. Am I right in saying the `data-prep` in that is essentially the same in the m6anet tool set? If so can I used the files I've already generated with m6anet-inference. Or is the `m6anet dataprep` install different to the `xpore` version? 

Is it possible to site-specific differential analysis after running `m6anet-inference`? 

May I ask what guppy version have you used to train? I currently have lots of DRS data basecalled with v3.4.5 but I think they may have updated the accuracy slightly in v3.6-ish ? You'd expect similar accuracy for m6A calls using different guppy versions?

**Comment by chrishendra93** [comment]
hi @callumparr, thanks for trying out m6anet and sorry for the delay in my response

Currently the dataprep method that m6anet differs from xpore in terms of the features generated and therefore we are not able to use the eventalign.hdf5 generated from xpore. We are planning to integrate the preprocessing steps in the future so stay tune!

To answer your second question, the current release of m6anet, the probability score that it generates is not correlated with the proportion of modified reads a site has so it is not able to run differential analysis. The next release will have some quantification features and we might be able to do differential modification analysis but currently we are still validating the quantification results

For the third question, the guppy version that we use is v2.1.3 so it is rather old but in principle this should not affect the accuracy of the algorithm. This is because we are using the current intensity features as generated by nanopolish eventalign and so it does not depend on the base-calling accuracy (although this probably might affect nanopolish eventalign)

**Comment by callumparr** [comment]
hey @chrishendra93 thank you for the in-depth reply. It is very useful. Look forward to new releases of m6anet!
