### ISSUE TITLE
MIN_READS setting

### ISSUE THREAD

**Issue by xieyy46** [GoekeLab/m6anet#37]
Hi developer！If I want to include more sites from low expressed gene, can I just modify the MIN_READS setting (from 20 to 5) in run_inference.py ?

**Comment by chrishendra93** [comment]
hi @xieyy46 , currently we do not recommend changing the MIN_READS setting since the data is not trained using reads lower than 20. Part of this is because the m6A labels might not be very accurate for site with lowly expressed gene as the chance of those reads containing m6A will be relatively low especially if the m6A stoichiometry is not high to begin with. We'll try to benchmark the performance for the next update using lower number of reads and see if we can do anything about this
