### ISSUE TITLE
m6anet inference pooling replicates 

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/m6anet#98]
It says in the documentation that m6anet supports pooling replicates.
But m6anet keeps giving me this error when I fed in multiple dataprep directories for each sample.

"usage: m6anet-run_inference --input_dir INPUT_DIR --out_dir OUT_DIR
                            [--model_config MODEL_CONFIG]
                            [--model_state_dict MODEL_STATE_DICT]
                            [--batch_size BATCH_SIZE]
                            [--n_processes N_PROCESSES]
                            [--num_iterations NUM_ITERATIONS]
                            [--device DEVICE]
m6anet-run_inference: error: unrecognized arguments: results/m6anet/m6anet_dataprep/test_1/data.json results/m6anet/m6anet_dataprep/test_2/data.json results/m6anet/m6anet_dataprep/test_3/data.json"

Can you please elaborate on how I can feed in multiple dataprep results for m6anet inference?

**Comment by chrishendra93** [comment]
hi may I know which version you are using and the command that you ran? m6anet inference requires you to pass the directories separated by space, so if you are using the m6anet-run_inference API, it will be something like

m6anet-run_inference --input_dir dir1 dir2 dir3 

Note that you just need to pass directory test_1, test_2, and so on instead of test1_1/data.json and test_2/data.json

**Comment by sunsetyerin** [comment]
Hi @chrishendra93 
I tried with directory names containing .json files but it cannot recognize multiple input directories.
I used docker container "docker://docker.io/yuukiiwa/m6anet:1.0"

**Comment by chrishendra93** [comment]
hi @sunsetyerin , you are using an outdated version of m6anet that does not have the pooling capability. One way to fix this is to install the latest version from pip / GitHub.
